# vim ft=yaml
sudo: false  # To use travis container infrastructure
language: python

python:
    - 2.7
    - 3.4
    - 3.5

env:
    - CORE=
    - CORE=prescott
    - CORE=dunnington
    - CORE=penryn
    - CORE=core2
    - CORE=nehalem
    - CORE=sandybridge

matrix:
  include:
    # Run a narrow unicode build on trusty
    - python: 2.7
      dist: trusty
    - python: 3.4
      dist: trusty

before_install:
    - BLAS=openblas
    - virtualenv --python=python venv
    - source venv/bin/activate
    - python --version # just to check
    - python -m pip install -U pip
    - pip install -U wheel

install:
    - pip install --timeout=60 -r $BLAS-requirements.txt
    # Statsmodels latest release breaks with latest pandas; use recent trunk
    # commit
    - pip install cython
    - pip install https://github.com/statsmodels/statsmodels/archive/c89da5cb7c49c7bdd8699df6e7073ace43bd5250.zip

script:
    - export OPENBLAS_VERBOSE=2
    - if [ -n "$CORE" ]; then export OPENBLAS_CORETYPE=$CORE; fi
    - pip install nose
    # Change into an innocuous directory and find tests from installation
    - mkdir for_testing
    - cd for_testing
    - python -c 'import numpy; numpy.test("full")'
    - python -c 'import scipy; scipy.test("full")'
    - nosetests sklearn
    - nosetests numexpr
    # Exclude failing datetime conversion tests
    # https://github.com/pydata/pandas/issues/12729
    - nosetests --exe -A "not slow and not network and not disabled"
      -e test_parsers -e TestDatetimeParsingWrappers
      -e test_range_slice_seconds -e test_range_slice_day
      pandas
    # Exclude extremely slow statsmodels tests
    - nosetests -e test_vcomp_2 -e test_sarimax --verbosity=3 statsmodels
