# vim ft=yaml
sudo: false  # To use travis container infrastructure
language: python
python:
    - 2.7
    - 3.4
    - 3.5

env:
    - BLAS=atlas
    - BLAS=atlascustom
    - BLAS=openblas
    - BLAS=openblas CORE=prescott
    - BLAS=openblas CORE=dunnington
    - BLAS=openblas CORE=penryn
    - BLAS=openblas CORE=core2
    - BLAS=openblas CORE=nehalem
    - BLAS=openblas CORE=sandybridge

before_install:
    - virtualenv --python=python venv
    - source venv/bin/activate
    - python --version # just to check
    - python -m pip install -U pip
    - pip install -U wheel

install:
    - pip install --timeout=60 -r $BLAS-requirements.txt
    # Statsmodels latest release breaks with latest pandas; use recent trunk
    # commit
    - pip install cython
    - pip install https://github.com/statsmodels/statsmodels/archive/eed4ae5a90a1d1ac312c24bbebf2bff88fe87da9.zip

script:
    - export OPENBLAS_VERBOSE=2
    - if [ -n "$CORE" ]; then export OPENBLAS_CORETYPE=$CORE; fi
    - pip install nose
    # Change into an innocuous directory and find tests from installation
    - mkdir for_testing
    - cd for_testing
    - python -c 'import numpy; numpy.test("full")'
    - python -c 'import scipy; scipy.test("full")'
    - nosetests sklearn
    - nosetests numexpr
    - nosetests --exe -A "not slow and not network and not disabled" -e test_parsers -e TestDatetimeParsingWrappers pandas
    - nosetests -e test_vcomp_2 --verbosity=3 statsmodels
