# vim ft=yaml
sudo: false  # To use travis container infrastructure
language: python
python:
    - 2.7
    - 3.4
    - 3.5

env:
    - BLAS=atlas
    - BLAS=atlascustom
    - BLAS=openblas CORE=prescott
    - BLAS=openblas CORE=core2
    - BLAS=openblas CORE=nehalem
    - BLAS=openblas CORE=sandybridge
    - BLAS=openblas CORE=haswell
    - BLAS=openblas CORE=bulldozer
    - BLAS=openblas CORE=piledriver
    - BLAS=openblas CORE=steamroller

before_install:
    - virtualenv --python=python venv
    - source venv/bin/activate
    - python --version # just to check
    - python -m pip install -U pip
    - pip install -U wheel

install:
    - pip install --timeout=60 -r $BLAS-requirements.txt
    # Statsmodels latest release breaks with latest pandas; use current trunk
    - pip install -f https://nipy.bic.berkeley.edu/manylinux cython==0.23.4
    - pip install -U --pre git+https://github.com/statsmodels/statsmodels@eed4ae5a90a1d1ac312c24bbebf2bff88fe87da9

script:
    - if [ "$BLAS" == "openblas" ]; then
          PREFIX="OPENBLAS_VERBOSE=2 OPENBLAS_CORETYPE=$CORE";
      fi
    - pip install nose
    # Change into an innocuous directory and find tests from installation
    - mkdir for_testing
    - cd for_testing
    - $PREFIX python -c 'import numpy; numpy.test("full")'
    - $PREFIX python -c 'import scipy; scipy.test("full")'
    - $PREFIX python -c 'import statsmodels; statsmodels.test("full")'
    - $PREFIX nosetests sklearn
    - $PREFIX nosetests numexpr
    - $PREFIX nosetests --exe -A "not slow and not network and not disabled" -e test_parsers -e TestDatetimeParsingWrappers pandas
