# vim ft=yaml
sudo: false  # To use travis container infrastructure
language: python
env:
    global:
        - REQUIREMENTS=openblas-requirements.txt
        - SCRIPT=test_blas_packages.sh
        - MPL_VERSION=1.5.3
        # Comment out to disable pre-release versions
        # - PRE="--pre"

matrix:
  include:
    - python: 2.7
      env:
        - SCRIPT=test_mpl.sh
        - REQUIREMENTS=mpl-requirements.txt
    - python: 2.7
      dist: trusty
      env:
        - SCRIPT=test_mpl.sh
        - REQUIREMENTS=mpl-requirements.txt
    - python: 3.5
      dist: trusty
      env:
        - SCRIPT=test_mpl.sh
        - REQUIREMENTS=mpl-requirements.txt
    - python: 3.4
      env:
        - SCRIPT=test_mpl.sh
        - REQUIREMENTS=mpl-requirements.txt
    - python: 3.5
      env:
        - SCRIPT=test_mpl.sh
        - REQUIREMENTS=mpl-requirements.txt
    # Run a narrow and wide unicode build on trusty
    - python: 2.7
      dist: trusty
    - python: 3.5
      dist: trusty
    - python: 2.7
      env:
         - CORE=
    - python: 2.7
      env:
         - CORE=prescott
    - python: 2.7
      env:
         - CORE=dunnington
    - python: 2.7
      env:
         - CORE=penryn
    - python: 2.7
      env:
         - CORE=core2
    - python: 2.7
      env:
         - CORE=nehalem
    - python: 2.7
      env:
         - CORE=sandybridge
    - python: 3.4
      env:
         - CORE=
    - python: 3.5
      env:
         - CORE=
    - python: 3.5
      env:
         - CORE=prescott
    - python: 3.5
      env:
         - CORE=dunnington
    - python: 3.5
      env:
         - CORE=penryn
    - python: 3.5
      env:
         - CORE=core2
    - python: 3.5
      env:
         - CORE=nehalem
    - python: 3.5
      env:
         - CORE=sandybridge

before_install:
    - virtualenv --python=python venv
    - source venv/bin/activate
    - python --version # just to check
    - python -m pip install -U pip
    - pip install -U wheel

install:
    - pip install --timeout=60 $PRE -r $REQUIREMENTS

script:
    - pip install nose
    # Change into an innocuous directory and find tests from installation
    - mkdir for_testing
    - cd for_testing
    - source ../$SCRIPT
